version: 0.1.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore Scopes.sln
- nuget restore Scopes.Engine\Scopes.Engine.csproj
- nuget restore Scopes.Engine.Tests\Scopes.Engine.Tests.csproj
build:
  verbosity: normal
artifacts:
- path: Scopes.Engine.Tests\coverage
  name: Coverage